[package]
name = "waridley-aoc-2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
num_cpus = "1.14.0"

[profile.dev]
opt-level = 2