name: CI

on: [push]

env:
  TZ: :US/Eastern

jobs:
    run:
        name: Run
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - uses: actions/cache@v3
          with:
            path: |
                ~/.cargo/bin/
                ~/.cargo/registry/index/
                ~/.cargo/registry/cache/
                ~/.cargo/git/db/
                target/
            key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

        - name: Rust toolchain
          uses: dtolnay/rust-toolchain@beta

        - name: Test part 1
          run: cargo test --lib $(date +'day_%d::part_1')
        - name: Run part 1
          run: cargo run --bin $(date +'day_%d_part_1')

        - name: Test part 2
          run: cargo test --lib $(date +'day_%d::part_2')
        - name: Run part 2
          run: cargo run --bin $(date +'day_%d_part_2')
    